/// 猫耳の女の子「ヤメにゃん」の高解像度ドット絵データ。
///
/// 画像ファイルは使わず、64x80 の文字グリッドをコードで描画する。
/// grids は tool（Python）で手続き生成して焼き込んだもの。
library;

enum Mood { great, good, worried, bad }

class CatArt {
  const CatArt._();

  static const Map<Mood, List<String>> _grids = <Mood, List<String>>{
    Mood.great: <String>[
      '................................................................',
      '................................................................',
      '....................kkk..................kkk....................',
      '....................kyk..................kYk....................',
      '....................kykk.................kYk....................',
      '...................kkyyk................kkYkk...................',
      '...................kyyykk...............kYYYk...................',
      '...................kyyyyk..............kkYYYkk..................',
      '..................kkypyykk.............kyYpYYk..................',
      '..................kyypyyyk.....kkk....kkyYpYYk..................',
      '..................kyyppyykkkkkkkykkkkkkyyYpYYkk.................',
      '.................kkypppyyykyyyyyyyyyyykyypppYYk.................',
      '.................kyyppppyyyyyyyyyyyyyyyyypppYYkk................',
      '................kkyyppppyyyyyyyyyyyyyyyypppppYYk................',
      '................kyyppppppyyyyyyyyyyyyyyypppppYYkk...............',
      '................kyypppppyyyyyyyyyyyyyyyyyppppYYYk...............',
      '...............kkyyppppyYYYYYYYYYYYYYYYYYgppppggk...............',
      '............q..kyyppppyyYYYYYYYYYYYYYYYYYggpppggkk..............',
      '...........qqq.kyypppyyyYYYYYYYYYYYYYYYYYgggpppggk..............',
      '............q.kkyypppyyyYYYYYYYYYYYYYYYYYgggpppggkk.q...........',
      '..............kyypyyyyyyYYYYYYYYYYYYYYYYYggggggpggkqqq..........',
      '.............kkyyyyyyyyyYYYYYYYYYYYYYYYYYgggggggggkkq...........',
      '.............kyyyyyyyyyyYYYYYYYYsYYYYYYYYggggggggggk............',
      '.............kyyyyyyyyyyYYYYYYYAAYYYYYYYYggggggggggk............',
      '.............kyyyyyyyyyyYYYYYYYAAYYYYYYYYggggggggggk............',
      '............kkyyyyyyyyyyYYYYYYYaaYYYYYYYYggggggggggkk...........',
      '............kyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '............kyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '............kyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '...........kkyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '...........kYYYYYYYYYYYYgggggggggggggggggGGGGGGGGGGGk...........',
      '...........kYYYYYYYYYYGGGGGGGgggggggGGGGGGGGGGGGGGGGk...........',
      '...........kYYYYYYYYYYYYgggggggggggggggggGGGGGGGGGGGkk..........',
      '...........kYYYYYYYYYYYYwwwaaaaaaaaAAAwwwGGGGGGGGGGGGk..........',
      '...........kkYYYYYYYYYYkkkkkaaaaaaaAAkkkkkGGGGGGGGGGkk..........',
      '............kYYYYYYYkkkwIIIwkkaaaakkkwIIIwkkGGGGGGGGk...........',
      '............kYYYYYYYYYwIhiIIwakaaaAAwIhiIIwGkGGGGGGGk...........',
      '............kYYYYYYYYwwIhiiIwwaaaAAwwIhiiIwwGGGGGGGGk...........',
      '............kYYYYYYYYwwIieiIwwaAAAAwwIieiIwwGGGGGGGGk...........',
      '..........q.kYYYYYYYYwwieeeiwwAAAAAwwieeeiwwGGGGGGGGk...........',
      '.........qqqkgggggggggwIiehIwAAAAAAAwIiehIwGGGGGGGGGk...........',
      '..........q.kkggggggggwIiiiIwAAAAAAAwIiiiIwGGGGGGGGkk...........',
      '.............kgggggggggwIiIwAAAAAAAAAwIiIwGGGGGGGGGk............',
      '.............kggggggggggwwwAAAAAAAAAAAwwwGGGGGGGGGGk...q........',
      '.............kggggggggggbAAAAAAAAAAAAAAAbGGGGGGGGGkk..qqq.......',
      '.............kggggggggggbbAAAAAAAAAAAAAbbGGGGGGGGGk....q........',
      '.............kggggggggggbAAAAAAAAAAAAAAAbGGGGGGGGGk.............',
      '.............kkggggggggggsAAAAAAsAAAAAAsgGGGGGGGGkkkkk..........',
      '..............kgggggggggggssAAAAAAAAAssggGGGGGGGGkkkGkkk........',
      '..............kgggggggggggggsssAAAsssggggGGGGGGGGkGGGGGk........',
      '..............kgggggggggggggmgggsgggmggggGGGGGGGGkGGGGGkkk......',
      '..............kgggggggggggggmmmgggmmmggggGGGGGGGGGGGGGGGGkkk....',
      '..............kGGGGGGGGGGGGGGmmmmmmmGGGGGGGGGGGGGkGGGGGGGGGk....',
      '..............kGGGGGGGkGGGGGGGGmmmGGGGGGGGGGGGGGGkGGGGGGGGGkk...',
      '..............kkGGGGGGkkGGGGGGGGGGGGGGGGGkGGGGGGkkkkGGGGGGGGk...',
      '...............kGGGGGGkkkkkGGGGGGGGGGGkkkkGGGGGGk..kkkGGGGGkkk..',
      '...............kGGGGGGk...kkssAAAAAAkkk..kGGGGGGk....kGGGGGGGkk.',
      '...............kGGGGGGk....kssAAAAAAk....kGGGGGGk....kkGGGGGGGk.',
      '...............kGGGGGGk....kssAAAAAAk....kGGGGGGk....kkGGGGGGGkk',
      '...............kGGGGGGk....kssAAAAAAk....kGGGGGGk....kGGGGGGGGGk',
      '...............kkGGGGGk....kssAAAAAAk....kGGGGGkk....kkGGGGGGGkk',
      '................kGGGGGkkkkkkssAAAAAAkkkkkkGGGGGk......kGGGGGGGk.',
      '................kGDDddddddddssAAAAAAddddddddDDDkk....kkGGGGGGkk.',
      '..............kkkDDDddddddddssAAAAAAddddddddDDDDkkk..kGGGGGGGk..',
      '.............kkDDDDDdddddddddlllllldddddddddDDDDDDkkkkGGGGGGGkk.',
      '............kkDDDDDDdddddddddlllllldddddddddDDDDDDDkkGGGGGGGGGk.',
      '............kDDDDDDDdddddddddlllllldddddddddDDDDDDDDGGGGGGGGGkk.',
      '...........kkDDDDDDDdddddddddlllllldddddddddDDDDDDDDGGGGGGGGGk..',
      '...........kDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDGGGGGGGkk..',
      '..........kkDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDGGGGGGkk...',
      '..........kDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGGk...',
      '..........kDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGkk...',
      '..........kDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGk....',
      '.........kkDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGk....',
      '........kkDDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDDGGGkk....',
      '........kDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDkkk.....',
      '........kDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDk.......',
      '.......kkDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDkk......',
      '.......kDDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDDk......',
      '.......kkDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDkk......',
    ],
    Mood.good: <String>[
      '................................................................',
      '................................................................',
      '....................kkk..................kkk....................',
      '....................kyk..................kYk....................',
      '....................kykk.................kYk....................',
      '...................kkyyk................kkYkk...................',
      '...................kyyykk...............kYYYk...................',
      '...................kyyyyk..............kkYYYkk..................',
      '..................kkypyykk.............kyYpYYk..................',
      '..................kyypyyyk.....kkk....kkyYpYYk..................',
      '..................kyyppyykkkkkkkykkkkkkyyYpYYkk.................',
      '.................kkypppyyykyyyyyyyyyyykyypppYYk.................',
      '.................kyyppppyyyyyyyyyyyyyyyyypppYYkk................',
      '................kkyyppppyyyyyyyyyyyyyyyypppppYYk................',
      '................kyyppppppyyyyyyyyyyyyyyypppppYYkk...............',
      '................kyypppppyyyyyyyyyyyyyyyyyppppYYYk...............',
      '...............kkyyppppyYYYYYYYYYYYYYYYYYgppppggk...............',
      '...............kyyppppyyYYYYYYYYYYYYYYYYYggpppggkk..............',
      '...............kyypppyyyYYYYYYYYYYYYYYYYYgggpppggk..............',
      '..............kkyypppyyyYYYYYYYYYYYYYYYYYgggpppggkk.............',
      '..............kyypyyyyyyYYYYYYYYYYYYYYYYYggggggpggk.............',
      '.............kkyyyyyyyyyYYYYYYYYYYYYYYYYYgggggggggkk............',
      '.............kyyyyyyyyyyYYYYYYYYsYYYYYYYYggggggggggk............',
      '.............kyyyyyyyyyyYYYYYYYAAYYYYYYYYggggggggggk............',
      '.............kyyyyyyyyyyYYYYYYYAAYYYYYYYYggggggggggk............',
      '............kkyyyyyyyyyyYYYYYYYaaYYYYYYYYggggggggggkk...........',
      '............kyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '............kyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '............kyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '...........kkyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '...........kYYYYYYYYYYYYgggggggggggggggggGGGGGGGGGGGk...........',
      '...........kYYYYYYYYYYGGGGGGGgggggggGGGGGGGGGGGGGGGGk...........',
      '...........kYYYYYYYYYYYYgggggggggggggggggGGGGGGGGGGGkk..........',
      '...........kYYYYYYYYYYYYwwwaaaaaaaaAAAwwwGGGGGGGGGGGGk..........',
      '...........kkYYYYYYYYYYkkkkkaaaaaaaAAkkkkkGGGGGGGGGGkk..........',
      '............kYYYYYYYkkkwIIIwkkaaaakkkwIIIwkkGGGGGGGGk...........',
      '............kYYYYYYYYYwIhiIIwakaaaAAwIhiIIwGkGGGGGGGk...........',
      '............kYYYYYYYYwwIhiiIwwaaaAAwwIhiiIwwGGGGGGGGk...........',
      '............kYYYYYYYYwwIieiIwwaAAAAwwIieiIwwGGGGGGGGk...........',
      '............kYYYYYYYYwwieeeiwwAAAAAwwieeeiwwGGGGGGGGk...........',
      '............kgggggggggwIieiIwAAAAAAAwIieiIwGGGGGGGGGk...........',
      '............kkggggggggwIiiiIwAAAAAAAwIiiiIwGGGGGGGGkk...........',
      '.............kgggggggggwIiIwAAAAAAAAAwIiIwGGGGGGGGGk............',
      '.............kggggggggggwwwAAAAAAAAAAAwwwGGGGGGGGGGk............',
      '.............kggggggggggbAAAAAAAAAAAAAAAbGGGGGGGGGkk............',
      '.............kggggggggggbbAAAAAAAAAAAAAbbGGGGGGGGGk.............',
      '.............kggggggggggbAAAAAAAAAAAAAAAbGGGGGGGGGk.............',
      '.............kkggggggggggsAAAAAAsAAAAAAsgGGGGGGGGkkkkk..........',
      '..............kgggggggggggssAAAAAAAAAssggGGGGGGGGkkkGkkk........',
      '..............kgggggggggggggsssAAAsssggggGGGGGGGGkGGGGGk........',
      '..............kgggggggggggggggggsggggggggGGGGGGGGkGGGGGkkk......',
      '..............kggggggggggggggmmgggmmgggggGGGGGGGGGGGGGGGGkkk....',
      '..............kGGGGGGGGGGGGGGGGmmmGGGGGGGGGGGGGGGkGGGGGGGGGk....',
      '..............kGGGGGGGkGGGGGGGGGGGGGGGGGGGGGGGGGGkGGGGGGGGGkk...',
      '..............kkGGGGGGkkGGGGGGGGGGGGGGGGGkGGGGGGkkkkGGGGGGGGk...',
      '...............kGGGGGGkkkkkGGGGGGGGGGGkkkkGGGGGGk..kkkGGGGGkkk..',
      '...............kGGGGGGk...kkssAAAAAAkkk..kGGGGGGk....kGGGGGGGkk.',
      '...............kGGGGGGk....kssAAAAAAk....kGGGGGGk....kkGGGGGGGk.',
      '...............kGGGGGGk....kssAAAAAAk....kGGGGGGk....kkGGGGGGGkk',
      '...............kGGGGGGk....kssAAAAAAk....kGGGGGGk....kGGGGGGGGGk',
      '...............kkGGGGGk....kssAAAAAAk....kGGGGGkk....kkGGGGGGGkk',
      '................kGGGGGkkkkkkssAAAAAAkkkkkkGGGGGk......kGGGGGGGk.',
      '................kGDDddddddddssAAAAAAddddddddDDDkk....kkGGGGGGkk.',
      '..............kkkDDDddddddddssAAAAAAddddddddDDDDkkk..kGGGGGGGk..',
      '.............kkDDDDDdddddddddlllllldddddddddDDDDDDkkkkGGGGGGGkk.',
      '............kkDDDDDDdddddddddlllllldddddddddDDDDDDDkkGGGGGGGGGk.',
      '............kDDDDDDDdddddddddlllllldddddddddDDDDDDDDGGGGGGGGGkk.',
      '...........kkDDDDDDDdddddddddlllllldddddddddDDDDDDDDGGGGGGGGGk..',
      '...........kDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDGGGGGGGkk..',
      '..........kkDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDGGGGGGkk...',
      '..........kDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGGk...',
      '..........kDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGkk...',
      '..........kDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGk....',
      '.........kkDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGk....',
      '........kkDDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDDGGGkk....',
      '........kDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDkkk.....',
      '........kDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDk.......',
      '.......kkDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDkk......',
      '.......kDDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDDk......',
      '.......kkDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDkk......',
    ],
    Mood.worried: <String>[
      '................................................................',
      '................................................................',
      '....................kkk..................kkk....................',
      '....................kyk..................kYk....................',
      '....................kykk.................kYk....................',
      '...................kkyyk................kkYkk...................',
      '...................kyyykk...............kYYYk...................',
      '...................kyyyyk..............kkYYYkk..................',
      '..................kkypyykk.............kyYpYYk..................',
      '..................kyypyyyk.....kkk....kkyYpYYk..................',
      '..................kyyppyykkkkkkkykkkkkkyyYpYYkk.................',
      '.................kkypppyyykyyyyyyyyyyykyypppYYk.................',
      '.................kyyppppyyyyyyyyyyyyyyyyypppYYkk................',
      '................kkyyppppyyyyyyyyyyyyyyyypppppYYk................',
      '................kyyppppppyyyyyyyyyyyyyyypppppYYkk...............',
      '................kyypppppyyyyyyyyyyyyyyyyyppppYYYk...............',
      '...............kkyyppppyYYYYYYYYYYYYYYYYYgppppggk...............',
      '...............kyyppppyyYYYYYYYYYYYYYYYYYggpppggkk..............',
      '...............kyypppyyyYYYYYYYYYYYYYYYYYgggpppggk..............',
      '..............kkyypppyyyYYYYYYYYYYYYYYYYYgggpppggkk.............',
      '..............kyypyyyyyyYYYYYYYYYYYYYYYYYggggggpggk.............',
      '.............kkyyyyyyyyyYYYYYYYYYYYYYYYYYgggggggggkk............',
      '.............kyyyyyyyyyyYYYYYYYYsYYYYYYYYggggggggggk............',
      '.............kyyyyyyyyyyYYYYYYYAAYYYYYYYYggggggggggk............',
      '.............kyyyyyyyyyyYYYYYYYAAYYYYYYYYggggggggggk............',
      '............kkyyyyyyyyyyYYYYYYYaaYYYYYYYYggggggggggkk...........',
      '............kyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '............kyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '............kyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '...........kkyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '...........kYYYYYYYYYYYYgggggggggggggggggGGGGGtGGGGGk...........',
      '...........kYYYYYYYYYYGGGgggggggggggGGGggGGGGGGtGGGGk...........',
      '...........kYYYYYYYYYYYYgGGGgggggggggggGGGGGGGGGtGGGkk..........',
      '...........kYYYYYYYYYYYYwwwaGaaaaaaAAAwwwGGGGGGGGGGGGk..........',
      '...........kkYYYYYYYYYYkkkkkaaaaaaaAAkkkkkGGGGGGGGGGkk..........',
      '............kYYYYYYYkkkwIIIwkkaaaakkkwIIIwkkGGGGGGGGk...........',
      '............kYYYYYYYYYwIhiIIwakaaaAAwIhiIIwGkGGGGGGGk...........',
      '............kYYYYYYYYwwIhiiIwwaaaAAwwIhiiIwwGGGGGGGGk...........',
      '............kYYYYYYYYwwIieiIwwaAAAAwwIieiIwwGGGGGGGGk...........',
      '............kYYYYYYYYwwieeeiwwAAAAAwwieeeiwwGGGGGGGGk...........',
      '............kgggggggggwIieiIwAAAAAAAwIieiIwGGGGGGGGGk...........',
      '............kkggggggggwIiiiIwAAAAAAAwIiiiIwGGGGGGGGkk...........',
      '.............kgggggggggwIiIwAAAAAAAAAwIiIwGGGGGGGGGk............',
      '.............kggggggggggwwwAAAAAAAAAAAwwwGGGGGGGGGGk............',
      '.............kggggggggggbAAAAAAAAAAAAAAAbGGGGGGGGGkk............',
      '.............kggggggggggbbAAAAAAAAAAAAAbbGGGGGGGGGk.............',
      '.............kggggggggggbAAAAAAAAAAAAAAAbGGGGGGGGGk.............',
      '.............kkggggggggggsAAAAAAsAAAAAAsgGGGGGGGGkkkkk..........',
      '..............kgggggggggggssAAAAAAAAAssggGGGGGGGGkkkGkkk........',
      '..............kgggggggggggggsssAAAsssggggGGGGGGGGkGGGGGk........',
      '..............kgggggggggggggggggsggggggggGGGGGGGGkGGGGGkkk......',
      '..............kggggggggggggggggggggggggggGGGGGGGGGGGGGGGGkkk....',
      '..............kGGGGGGGGGGGGGGGmmmmmGGGGGGGGGGGGGGkGGGGGGGGGk....',
      '..............kGGGGGGGkGGGGGGGGGGGGGGGGGGGGGGGGGGkGGGGGGGGGkk...',
      '..............kkGGGGGGkkGGGGGGGGGGGGGGGGGkGGGGGGkkkkGGGGGGGGk...',
      '...............kGGGGGGkkkkkGGGGGGGGGGGkkkkGGGGGGk..kkkGGGGGkkk..',
      '...............kGGGGGGk...kkssAAAAAAkkk..kGGGGGGk....kGGGGGGGkk.',
      '...............kGGGGGGk....kssAAAAAAk....kGGGGGGk....kkGGGGGGGk.',
      '...............kGGGGGGk....kssAAAAAAk....kGGGGGGk....kkGGGGGGGkk',
      '...............kGGGGGGk....kssAAAAAAk....kGGGGGGk....kGGGGGGGGGk',
      '...............kkGGGGGk....kssAAAAAAk....kGGGGGkk....kkGGGGGGGkk',
      '................kGGGGGkkkkkkssAAAAAAkkkkkkGGGGGk......kGGGGGGGk.',
      '................kGDDddddddddssAAAAAAddddddddDDDkk....kkGGGGGGkk.',
      '..............kkkDDDddddddddssAAAAAAddddddddDDDDkkk..kGGGGGGGk..',
      '.............kkDDDDDdddddddddlllllldddddddddDDDDDDkkkkGGGGGGGkk.',
      '............kkDDDDDDdddddddddlllllldddddddddDDDDDDDkkGGGGGGGGGk.',
      '............kDDDDDDDdddddddddlllllldddddddddDDDDDDDDGGGGGGGGGkk.',
      '...........kkDDDDDDDdddddddddlllllldddddddddDDDDDDDDGGGGGGGGGk..',
      '...........kDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDGGGGGGGkk..',
      '..........kkDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDGGGGGGkk...',
      '..........kDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGGk...',
      '..........kDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGkk...',
      '..........kDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGk....',
      '.........kkDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGk....',
      '........kkDDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDDGGGkk....',
      '........kDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDkkk.....',
      '........kDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDk.......',
      '.......kkDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDkk......',
      '.......kDDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDDk......',
      '.......kkDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDkk......',
    ],
    Mood.bad: <String>[
      '................................................................',
      '................................................................',
      '....................kkk..................kkk....................',
      '....................kyk..................kYk....................',
      '....................kykk.................kYk....................',
      '...................kkyyk................kkYkk...................',
      '...................kyyykk...............kYYYk...................',
      '...................kyyyyk..............kkYYYkk..................',
      '..................kkypyykk.............kyYpYYk..................',
      '..................kyypyyyk.....kkk....kkyYpYYk..................',
      '..................kyyppyykkkkkkkykkkkkkyyYpYYkk.................',
      '.................kkypppyyykyyyyyyyyyyykyypppYYk.................',
      '.................kyyppppyyyyyyyyyyyyyyyyypppYYkk................',
      '................kkyyppppyyyyyyyyyyyyyyyypppppYYk................',
      '................kyyppppppyyyyyyyyyyyyyyypppppYYkk...............',
      '................kyypppppyyyyyyyyyyyyyyyyyppppYYYk...............',
      '...............kkyyppppyYYYYYYYYYYYYYYYYYgppppggk...............',
      '...............kyyppppyyYYYYYYYYYYYYYYYYYggpppggkk..............',
      '...............kyypppyyyYYYYYYYYYYYYYYYYYgggpppggk..............',
      '..............kkyypppyyyYYYYYYYYYYYYYYYYYgggpppggkk.............',
      '..............kyypyyyyyyYYYYYYYYYYYYYYYYYggggggpggk.............',
      '.............kkyyyyyyyyyYYYYYYYYYYYYYYYYYgggggggggkk............',
      '.............kyyyyyyyyyyYYYYYYYYsYYYYYYYYggggggggggk............',
      '.............kyyyyyyyyyyYYYYYYYAAYYYYYYYYggggggggggk............',
      '.............kyyyyyyyyyyYYYYYYYAAYYYYYYYYggggggggggk............',
      '............kkyyyyyyyyyyYYYYYYYaaYYYYYYYYggggggggggkk...........',
      '............kyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '............kyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '............kyyyyyyyyyyyYYYYYYYaaYYYYYYYYggoogggggggk...........',
      '...........kkyyyyyyyyyyyYYYYYYYaaYYYYYYYYgggggggggggk...........',
      '...........kYYYYYYYYYYYYgggggggggggggggggGGGGGGGGGGGk...........',
      '...........kYYYYYYYYYYGGGgggggggggggGGGggGGGGGGGGGGGk...........',
      '...........kYYYYYYYYYYYYgGGGgggggggggggGGooGGGGGGGGGkk..........',
      '...........kYYYYYYYYYYYYAAAaGaaaaaaAAAAAAGGGGGGGGGGGGk..........',
      '...........kkYYYYYYYYYYAAAAAaaaaaaaAAAAAAAGGGGGGGGGGkk..........',
      '............kYYYYYYYYYAAAAAAAaaaaaaAAAAAAAAGGGGGGGGGk...........',
      '............kYYYYYYYYAAAAAAAAAaaaaAAAAAAAAAooGGGGGGGk...........',
      '............kYYYYYYYYkkkkkkkkkaaaAAkkkkkkkkkGGGGGGGGk...........',
      '............kYYYYYYYYwwIhiiIwwaAAAAwwIhiiIwwGGGGGGGGk...........',
      '............kYYYYYYYYwIiieiiIwAAAAAwIiieiiIwGGGGGGGGk...........',
      '............kgggggggggwiieiiwAAAAAAAwiieiooGGGGGGGGGk...........',
      '............kkggggggggwIiiiIwAAAAAAAwIiiiIwGGGGGGGGkk...........',
      '.............kgggggggggwItIwAAAAAAAAAwItIwGGGGGGGGGk............',
      '.............kggggggggbsstsssAAAAAAAssstssbGGGGGGGGk............',
      '.............kggggggggggbtAAAAAAAAAAAAAtbGGooGGGGGkk............',
      '.............kggggggggggbtAAAAAAAAAAAAAtbGGGGGGGGGk.............',
      '.............kggggggggggbtAAAAAAAAAAAAAtbGGGGGGGGGk.............',
      '.............kkggggggggggtAAAAAAsAAAAAAtgGGGGGGGGkkkkk..........',
      '..............kgggggggggggssAAAAAAAAAssggGooGGGGGkkkGkkk........',
      '..............kgggggggggggggsssAAAsssggggGGGGGGGGkGGGGGk........',
      '..............kgggggggggggggggggsggggggggGGGGGGGGkGGGGGkkk......',
      '..............kgggggggggggggggggggccccccccrGGGGGGGGGGGGGGkkk....',
      '..............kGGGGGGGGGGGGGGGGmmmccccccccrGGGGGGkGGGGGGGGGk....',
      '..............kGGGGGGGkGGGGGGmmGGGmmGGGGGGGGGGGGGkGGGGGGGGGkk...',
      '..............kkGGGGGGkkGGGGGGGGGGGGGGGGGkGGGGGGkkkkGGGGGGGGk...',
      '...............kGGGGGGkkkkkGGGGGGGGGGGkkkkGGGGGGk..kkkGGGGGkkk..',
      '...............kGGGGGGk...kkssAAAAAAkkk..kGGGGGGk....kGGGGGGGkk.',
      '...............kGGGGGGk....kssAAAAAAk....kGGGGGGk....kkGGGGGGGk.',
      '...............kGGGGGGk....kssAAAAAAk....kGGGGGGk....kkGGGGGGGkk',
      '...............kGGGGGGk....kssAAAAAAk....kGGGGGGk....kGGGGGGGGGk',
      '...............kkGGGGGk....kssAAAAAAk....kGGGGGkk....kkGGGGGGGkk',
      '................kGGGGGkkkkkkssAAAAAAkkkkkkGGGGGk......kGGGGGGGk.',
      '................kGDDddddddddssAAAAAAddddddddDDDkk....kkGGGGGGkk.',
      '..............kkkDDDddddddddssAAAAAAddddddddDDDDkkk..kGGGGGGGk..',
      '.............kkDDDDDdddddddddlllllldddddddddDDDDDDkkkkGGGGGGGkk.',
      '............kkDDDDDDdddddddddlllllldddddddddDDDDDDDkkGGGGGGGGGk.',
      '............kDDDDDDDdddddddddlllllldddddddddDDDDDDDDGGGGGGGGGkk.',
      '...........kkDDDDDDDdddddddddlllllldddddddddDDDDDDDDGGGGGGGGGk..',
      '...........kDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDGGGGGGGkk..',
      '..........kkDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDGGGGGGkk...',
      '..........kDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGGk...',
      '..........kDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGkk...',
      '..........kDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGk....',
      '.........kkDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDGGGGGk....',
      '........kkDDDDDDDDDDdddddddddlllllldddddddddDDDDDDDDDDDGGGkk....',
      '........kDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDkkk.....',
      '........kDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDk.......',
      '.......kkDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDkk......',
      '.......kDDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDDk......',
      '.......kkDDDDDDDDDDDDDDDDDDDDllllllDDDDDDDDDDDDDDDDDDDDDkk......',
    ],
  };

  static List<String> forMood(Mood mood) => _grids[mood]!;

  static String message(Mood mood) {
    switch (mood) {
      case Mood.great:
        return '今日はまだゼロ本！さいこうにゃ〜！';
      case Mood.good:
        return 'へらせてるね、えらいにゃ〜！';
      case Mood.worried:
        return 'んー、ちょっと多いかも。深呼吸しよ？';
      case Mood.bad:
        return 'ゴホッ…むりしないで休もうにゃ。また一緒にがんばろ？';
    }
  }

  static String statusLabel(Mood mood) {
    switch (mood) {
      case Mood.great:
        return 'ぜっこうちょう！';
      case Mood.good:
        return 'いいペース';
      case Mood.worried:
        return 'ちょっと注意';
      case Mood.bad:
        return 'ひとやすみ';
    }
  }
}
